//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace BethanysPieShopStockApp.iOS.BethanysPieShopRemoteServices {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="PieAsmxServiceSoap", Namespace="http://tempuri.org/")]
    public partial class PieAsmxService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetAllPiesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPieByIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddPieOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdatePieOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeletePieOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public PieAsmxService() {
            this.Url = "https://bethanyspieshopstockappasmxservice.azurewebsites.net/PieAsmxService.asmx";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetAllPiesCompletedEventHandler GetAllPiesCompleted;
        
        /// <remarks/>
        public event GetPieByIdCompletedEventHandler GetPieByIdCompleted;
        
        /// <remarks/>
        public event AddPieCompletedEventHandler AddPieCompleted;
        
        /// <remarks/>
        public event UpdatePieCompletedEventHandler UpdatePieCompleted;
        
        /// <remarks/>
        public event DeletePieCompletedEventHandler DeletePieCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAllPies", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Pie[] GetAllPies() {
            object[] results = this.Invoke("GetAllPies", new object[0]);
            return ((Pie[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAllPiesAsync() {
            this.GetAllPiesAsync(null);
        }
        
        /// <remarks/>
        public void GetAllPiesAsync(object userState) {
            if ((this.GetAllPiesOperationCompleted == null)) {
                this.GetAllPiesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllPiesOperationCompleted);
            }
            this.InvokeAsync("GetAllPies", new object[0], this.GetAllPiesOperationCompleted, userState);
        }
        
        private void OnGetAllPiesOperationCompleted(object arg) {
            if ((this.GetAllPiesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllPiesCompleted(this, new GetAllPiesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetPieById", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Pie GetPieById(System.Guid id) {
            object[] results = this.Invoke("GetPieById", new object[] {
                        id});
            return ((Pie)(results[0]));
        }
        
        /// <remarks/>
        public void GetPieByIdAsync(System.Guid id) {
            this.GetPieByIdAsync(id, null);
        }
        
        /// <remarks/>
        public void GetPieByIdAsync(System.Guid id, object userState) {
            if ((this.GetPieByIdOperationCompleted == null)) {
                this.GetPieByIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPieByIdOperationCompleted);
            }
            this.InvokeAsync("GetPieById", new object[] {
                        id}, this.GetPieByIdOperationCompleted, userState);
        }
        
        private void OnGetPieByIdOperationCompleted(object arg) {
            if ((this.GetPieByIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPieByIdCompleted(this, new GetPieByIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddPie", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AddPie(Pie pie) {
            this.Invoke("AddPie", new object[] {
                        pie});
        }
        
        /// <remarks/>
        public void AddPieAsync(Pie pie) {
            this.AddPieAsync(pie, null);
        }
        
        /// <remarks/>
        public void AddPieAsync(Pie pie, object userState) {
            if ((this.AddPieOperationCompleted == null)) {
                this.AddPieOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddPieOperationCompleted);
            }
            this.InvokeAsync("AddPie", new object[] {
                        pie}, this.AddPieOperationCompleted, userState);
        }
        
        private void OnAddPieOperationCompleted(object arg) {
            if ((this.AddPieCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddPieCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdatePie", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UpdatePie(Pie pie) {
            this.Invoke("UpdatePie", new object[] {
                        pie});
        }
        
        /// <remarks/>
        public void UpdatePieAsync(Pie pie) {
            this.UpdatePieAsync(pie, null);
        }
        
        /// <remarks/>
        public void UpdatePieAsync(Pie pie, object userState) {
            if ((this.UpdatePieOperationCompleted == null)) {
                this.UpdatePieOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdatePieOperationCompleted);
            }
            this.InvokeAsync("UpdatePie", new object[] {
                        pie}, this.UpdatePieOperationCompleted, userState);
        }
        
        private void OnUpdatePieOperationCompleted(object arg) {
            if ((this.UpdatePieCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdatePieCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeletePie", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void DeletePie(System.Guid id) {
            this.Invoke("DeletePie", new object[] {
                        id});
        }
        
        /// <remarks/>
        public void DeletePieAsync(System.Guid id) {
            this.DeletePieAsync(id, null);
        }
        
        /// <remarks/>
        public void DeletePieAsync(System.Guid id, object userState) {
            if ((this.DeletePieOperationCompleted == null)) {
                this.DeletePieOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeletePieOperationCompleted);
            }
            this.InvokeAsync("DeletePie", new object[] {
                        id}, this.DeletePieOperationCompleted, userState);
        }
        
        private void OnDeletePieOperationCompleted(object arg) {
            if ((this.DeletePieCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeletePieCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Pie {
        
        private System.Guid idField;
        
        private string pieNameField;
        
        private string descriptionField;
        
        private double priceField;
        
        private string imageUrlField;
        
        private bool inStockField;
        
        /// <remarks/>
        public System.Guid Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string PieName {
            get {
                return this.pieNameField;
            }
            set {
                this.pieNameField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public double Price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
            }
        }
        
        /// <remarks/>
        public string ImageUrl {
            get {
                return this.imageUrlField;
            }
            set {
                this.imageUrlField = value;
            }
        }
        
        /// <remarks/>
        public bool InStock {
            get {
                return this.inStockField;
            }
            set {
                this.inStockField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetAllPiesCompletedEventHandler(object sender, GetAllPiesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllPiesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllPiesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Pie[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Pie[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetPieByIdCompletedEventHandler(object sender, GetPieByIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPieByIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPieByIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Pie Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Pie)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void AddPieCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void UpdatePieCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void DeletePieCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591